spring:
  application:
    name: ai-resume-analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/resume_analyzer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gemini:
  api-key: 
  model: gemini-2.0-flash-lite

storage:
  local:
    base-path: ./uploads/resumes

security:
  api-key: local-dev-key

logging:
  level:
    root: INFO
